### ISSUE TITLE
Project setup issues

### ISSUE THREAD

**Issue by 3sanket3** [varit05/chocomama#7]
After installing node_modules when I tried to run `npm run dev` it gave me an error 'No ESLint Configure'.

I tried to configure the ESLint from below steps, just to get it run
`npm install eslint --save-dev`
`npx eslint --init` -> there was an interactive configuration option it asked to configure the eslint. After my answers to it, it created `.eslintrc.json` file in the root with following content 

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

Now If I run `npm run dev` it returns me below error

```
 error  in ./src/route/routes.js

Syntax Error: Unexpected token (5:21)

  3 |     name: "dashboard",
  4 |     path: "/",
> 5 |     component: () => import("@/components/Dashboard.vue"),
    |                      ^
  6 |     isPublic: false,
  7 |     title: "Dashboard"
  8 |   },
```

**Comment by 3sanket3** [comment]
@varit05 Also I am not sure how you are auto-formatting the code, please consider adding `prettier` if we are not using anything for auto formatting

**Comment by varit05** [comment]
Local set up Issue is acknowledged in below PR, Hence closing it.

https://github.com/varit05/chocomama/pull/8
